# Cloudflare Pages 配置
name = "prompt-manager"
compatibility_date = "2024-08-01"
pages_build_output_dir = "."

[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"

# KV namespaces - 这些将通过Cloudflare Pages仪表板配置
# 或者通过GitHub集成自动创建
[[env.production.kv_namespaces]]
binding = "PROMPT_DATA"
id = "" # 将通过Cloudflare Pages仪表板设置

[[env.production.kv_namespaces]]
binding = "USER_AUTH"
id = "" # 将通过Cloudflare Pages仪表板设置

[[env.preview.kv_namespaces]]
binding = "PROMPT_DATA"
preview_id = "" # 将通过Cloudflare Pages仪表板设置

[[env.preview.kv_namespaces]]
binding = "USER_AUTH"  
preview_id = "" # 将通过Cloudflare Pages仪表板设置