name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-check:
    runs-on: ubuntu-latest
    name: Build and Lint Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check file structure
        run: |
          echo "Checking project structure..."
          ls -la
          echo "✅ Project structure looks good"
          
      - name: Validate HTML files
        run: |
          echo "Validating HTML files..."
          if [ -f "index.html" ] && [ -f "prompt-manager.html" ]; then
            echo "✅ Required HTML files exist"
          else
            echo "❌ Missing required HTML files"
            exit 1
          fi
          
      - name: Check Functions structure
        run: |
          echo "Checking Cloudflare Functions..."
          if [ -d "functions" ] && [ -f "functions/_middleware.js" ]; then
            echo "✅ Cloudflare Functions structure is correct"
          else
            echo "❌ Functions directory structure is incorrect"
            exit 1
          fi
          
      - name: Build success
        run: |
          echo "🎉 All checks passed! Ready for Cloudflare Pages deployment."
          echo "Note: Actual deployment is handled by Cloudflare Pages GitHub integration."